[PHP]
memory_limit = 528M
max_execution_time = 60
max_input_time = 60
post_max_size = 8M
upload_max_filesize = 2M
error_reporting = E_ALL & ~E_DEPRECATED & ~E_STRICT
display_errors = On
date.timezone = "Mexico/General"

[Session]
session.save_path = "/var/sessions"
session.gc_maxlifetime = 28800
session.cookie_lifetime = 0
session.cookie_httponly = 1
session.use_strict_mode = 1
