version: "3.8"

services:
  # Servicio de intérprete PHP-FPM
  front-app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: front-app
    restart: always
    env_file:
      - .env
    volumes:
      - app-data:/var/www/html:rw
      - ./ws-logs:/var/www/html/ws-logs:rw
      - ./docs:/var/www/html/data/user/settingsUsersDocument:rw

  # Servidor web Nginx (balanceador/estáticos)
  nginx:
    image: nginx:alpine
    user: root
    container_name: front-app-nginx
    restart: always
    volumes:
      - app-data:/var/www/html:ro
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - front-app

volumes:
  app-data:
